services:
  - type: web
    name: esoko-backend
    env: python
    buildCommand: ./build.sh
    startCommand: daphne core.asgi:application --port 10000 --bind 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DEBUG
        value: "False"