# Generated by Django 5.0.4 on 2026-04-04 08:27

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(
                blank=True, 
                null=True, 
                upload_to='products/files/', 
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['exe', 'zip', 'dmg', 'sh', 'bin', 'msi'])]
            ),
        ),
    ]