# Generated by Django 5.0.4 on 2026-04-11 08:44

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_paidproduct_image_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="products/files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["exe", "zip", "dmg", "sh", "bin", "msi"]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "product")},
            },
        ),
        migrations.DeleteModel(
            name="PaidProduct",
        ),
    ]
