# Generated by Django 5.0.4 on 2026-05-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_product_file_orderitem_delete_paidproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="download_url_override",
            field=models.URLField(
                blank=True,
                help_text="External download URL (overrides Cloudinary file if set)",
                null=True,
            ),
        ),
    ]
