# Generated by Django 5.0.4 on 2026-05-20 06:11

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_create_default_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="author",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Book author (e-books)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="download_url_override",
            field=models.URLField(
                blank=True,
                help_text="External download URL (overrides uploaded file if set)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ebook_file",
            field=models.FileField(
                blank=True,
                help_text="Upload PDF, ePub or MOBI for e-books",
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="products/ebooks/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "epub", "mobi"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="products/files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "exe",
                            "zip",
                            "dmg",
                            "sh",
                            "bin",
                            "msi",
                            "mp4",
                            "mkv",
                            "pdf",
                            "epub",
                            "doc",
                            "docx",
                            "rar",
                            "7z",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="page_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of pages (e-books)", null=True
            ),
        ),
    ]
