# Generated by Django 5.0.4 on 2026-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
